# Generated by Django 3.1.2 on 2021-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210123_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='signup',
            name='branch',
            field=models.CharField(max_length=13),
        ),
    ]
