# Generated by Django 3.1.2 on 2021-01-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210125_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfiles',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
