# Generated by Django 3.1.2 on 2021-01-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210128_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notesfiles',
            new_name='notesfile',
        ),
    ]
